# Generated by Django 4.2.6 on 2023-10-30 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('categoria', models.CharField(max_length=20)),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('rut_empresa', models.CharField(max_length=30)),
                ('telefono_celular', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioJefe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('contrasena', models.CharField(max_length=20)),
                ('documento_identificador', models.CharField(max_length=30)),
                ('fecha_contratacion', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(max_length=20)),
                ('fecha_nacimiento', models.DateField()),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('contrasena', models.CharField(max_length=20)),
                ('documento_identificador', models.CharField(max_length=30)),
                ('fecha_contratacion', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.PositiveIntegerField()),
                ('tipo_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Transferencia bancaria', 'Transferencia bancaria')], max_length=25)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='punto_venta.producto')),
                ('usuario_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_empleado', to=settings.AUTH_USER_MODEL)),
                ('usuario_jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_jefe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_factura', 'Puede agregar facturas'), ('can_delete_factura', 'Puede eliminar facturas'), ('can_update_factura', 'Puede actualizar facturas')],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=20)),
                ('segundo_nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20)),
                ('segundo_apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.cliente')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Transferencia bancaria', 'Transferencia bancaria')], max_length=25)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_y_hora', models.DateTimeField(auto_now_add=True)),
                ('productos', models.ManyToManyField(to='punto_venta.producto')),
                ('servicios', models.ManyToManyField(to='punto_venta.servicio')),
                ('usuario_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_empleado', to=settings.AUTH_USER_MODEL)),
                ('usuario_jefe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletas_jefe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_boleta', 'Puede agregar boletas'), ('can_delete_boleta', 'Puede eliminar boletas'), ('can_update_boleta', 'Puede actualizar boletas')],
            },
        ),
    ]
