# Generated by Django 4.2.6 on 2023-12-04 22:09

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tipo_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Transferencia bancaria', 'Transferencia bancaria')], max_length=25)),
                ('monto_neto', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
            ],
            options={
                'permissions': [('can_add_boleta', 'Puede agregar boletas'), ('can_delete_boleta', 'Puede eliminar boletas'), ('can_update_boleta', 'Puede actualizar boletas')],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.PositiveIntegerField()),
                ('tipo_de_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta de crédito', 'Tarjeta de crédito'), ('Transferencia bancaria', 'Transferencia bancaria')], max_length=25)),
                ('monto_neto', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_jefe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_add_factura', 'Puede agregar facturas'), ('can_delete_factura', 'Puede eliminar facturas'), ('can_update_factura', 'Puede actualizar facturas')],
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('primer_nombre', models.CharField(max_length=20, null=True)),
                ('primer_apellido', models.CharField(max_length=20, null=True)),
                ('correo_electronico', models.EmailField(max_length=30)),
                ('contrasena', models.CharField(max_length=20, null=True, verbose_name='contraseña')),
                ('fecha_nacimiento', models.DateField()),
                ('direccion', models.CharField(max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('rut_empresa', models.CharField(max_length=30)),
                ('telefono_celular', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=50)),
                ('precio', models.PositiveIntegerField()),
                ('tiempo', models.DurationField()),
                ('imagen', models.ImageField(default='servicios/default.jpg', upload_to='servicios/')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='punto_venta.persona')),
            ],
            options={
                'verbose_name': 'Cliente',
            },
            bases=('punto_venta.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='punto_venta.persona')),
                ('documento_identificador', models.CharField(max_length=30)),
                ('fecha_contratacion', models.DateField()),
                ('afp', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Empleado',
            },
            bases=('punto_venta.persona',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=300)),
                ('categoria', models.CharField(max_length=20)),
                ('precio_compra', models.PositiveIntegerField()),
                ('precio_venta', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('imagen', models.ImageField(default='productos/default.jpg', upload_to='productos/')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='punto_venta.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='Factura_detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('numero_factura', models.IntegerField()),
                ('cantidad', models.PositiveIntegerField()),
                ('monto_unidad', models.PositiveIntegerField()),
                ('monto_neto', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.factura')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.proveedor'),
        ),
        migrations.CreateModel(
            name='Boleta_servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('monto_unidad', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_neto', models.PositiveIntegerField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.boleta')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.servicio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Boleta_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('monto_unidad', models.PositiveIntegerField()),
                ('monto_neto', models.PositiveIntegerField()),
                ('monto_iva', models.PositiveIntegerField()),
                ('monto_total', models.PositiveIntegerField()),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.boleta')),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.producto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='servicio',
            name='empleados',
            field=models.ManyToManyField(to='punto_venta.empleado'),
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='punto_venta.servicio')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.cliente'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='punto_venta.empleado'),
        ),
    ]
