# Generated by Django 4.2.7 on 2023-12-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_venta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(max_length=30, unique=True),
        ),
    ]
