# Generated by Django 4.2.6 on 2023-12-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_venta', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
