# Generated by Django 4.2.7 on 2023-11-29 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('punto_venta', '0004_alter_boleta_monto_iva_alter_boleta_monto_neto_and_more'),
        ('punto_venta', '0004_producto_imagen_alter_boleta_monto_iva_and_more'),
    ]

    operations = [
    ]
