# Generated by Django 4.2.7 on 2023-11-29 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punto_venta', '0007_persona_contrasena_persona_correo_electronico_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta_producto',
            old_name='precio_venta',
            new_name='monto_unidad',
        ),
        migrations.RenameField(
            model_name='boleta_servicio',
            old_name='precio_venta',
            new_name='monto_unidad',
        ),
        migrations.RenameField(
            model_name='factura_detalle',
            old_name='precio_venta',
            new_name='monto_unidad',
        ),
        migrations.AlterField(
            model_name='persona',
            name='contrasena',
            field=models.CharField(max_length=20, null=True, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='correo_electronico',
            field=models.EmailField(max_length=30),
        ),
    ]
